apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "atlas.fullname" . }}-postgres
          volumeMounts:
            - name: atlas-postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: atlas-postgres-data
          persistentVolumeClaim:
            claimName: atlas-postgres-pvc
