apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-postgres-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
