frontend:
  replicaCount: 1
  image:
    repository: 635218167984.dkr.ecr.ap-south-1.amazonaws.com/atlas-frontend
    tag: v1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 2
  image:
    repository: 635218167984.dkr.ecr.ap-south-1.amazonaws.com/atlas-backend
    tag: v2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000

postgres:
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  database: atlas
  username: atlas
  password: atlas

migration:
  enabled: false
  backoffLimit: 1
  ttlSecondsAfterFinished: 300

resources: {}
